tenants/all/templates/fm-today.marko, tenants/all/templates/id-today.marko, tenants/all/templates/impo-mag-today.marko, tenants/all/templates/manufacturing-today.marko, tenants/all/templates/mbt-today.marko, tenants/all/templates/newswire.marko, tenants/ien/templates/ien-today.marko
Link href updated from node.linkText to node.siteContext.url
=> Link text/CTA url bug fix

packages/common/components/blocks/content/featured-full.marko, packages/common/components/blocks/content/featured-half.marko, packages/common/components/blocks/content/feed-full.marko, packages/common/components/blocks/content/marko.json, packages/common/components/blocks/content/promotion-half.marko, packages/common/components/blocks/footer/index.marko, packages/common/components/blocks/footer/marko.json, packages/common/components/blocks/header/image-full.marko, packages/common/components/blocks/header/marko.json, packages/common/components/blocks/header/wrapper.marko, packages/common/components/blocks/marko.json, tenants/ien/config/core.js, tenants/ien/config/email-x.js, tenants/ien/templates/engineering-news-today.marko, tenants/ien/templates/finishing-world.marko, tenants/ien/templates/food-beverage-insider.marko, tenants/ien/templates/ien-today.marko, tenants/ien/templates/ien-update.marko, tenants/ien/templates/ien-weekly.marko, tenants/ien/templates/industrial-management-today.marko, tenants/ien/templates/industrial-software-technology.marko, tenants/ien/templates/industrial-technology-today.marko, tenants/ien/templates/product-showcase.marko, tenants/ien/templates/video-showcase.marko
(adding them as I go)
---
---
---
---
---
---
---
---
---
---
=> IEN Newsletter Migration

.travis.yml, docker-compose.yml, packages/common/components/blocks/content/featured-full.marko, tenants/cen/components/ad-unit.marko, tenants/cen/components/banner-element.marko, tenants/cen/components/marko.json, tenants/cen/config/core.js, tenants/cen/config/custom.js, tenants/cen/config/email-x.js, tenants/cen/config/gam.js, tenants/cen/index.js, tenants/cen/marko.json, tenants/cen/newrelic.js, tenants/cen/package.json, tenants/cen/templates/cen-today.marko, tenants/ddt/components/ad-unit.marko, tenants/ddt/components/banner-element.marko, tenants/ddt/components/marko.json, tenants/ddt/config/core.js, tenants/ddt/config/custom.js, tenants/ddt/config/email-x.js, tenants/ddt/config/gam.js, tenants/ddt/index.js, tenants/ddt/marko.json, tenants/ddt/newrelic.js, tenants/ddt/package.json, tenants/ddt/templates/design-development-today.marko, tenants/ddt/templates/design-development-update.marko
https://email.cannabisequipmentnews.com/cen-today/2019/05/31
https://email.designdevelopmenttoday.com/design-development-today/2020/03/11
https://email.designdevelopmenttoday.com/design-development-update/2020/03/11
=> Can't forget about the red-headed step-children

package.json, packages/common/package.json, tenants/multi/package.json, yarn.lock
=> Upgrade @base-cms dependenies to 1.36.1

tenants/multi/templates/cen-today.marko
=> Update CEN logo

tenants/multi/config/core.js
=> Add CEN social providers

packages/common/components/blocks/content/grid.marko, tenants/multi/config/email-x.js
- Add leaderboard
- Update layout of TextAds
=> Update IEN Today Refresh template

tenants/multi/templates/id-product-showcase.marko
=> Update ID PSC header image

packages/common/components/blocks/content/promotion-half.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-mag-today.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko
=> Make button text style the same

packages/common/components/blocks/footer/index.marko, tenants/multi/templates/fm-product-showcase.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/id-digital-edition.marko, tenants/multi/templates/id-product-showcase.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-mag-product-showcase.marko, tenants/multi/templates/impo-mag-today.marko, tenants/multi/templates/manufacturing-product-showcase.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/mbt-product-showcase.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko
https://parameter1.freshdesk.com/a/tickets/372
https://www.pivotaltracker.com/story/show/176421820
=> Remove phone # from enl footers

tenants/multi/templates/digital-edition.marko, tenants/multi/templates/id-digital-edition.marko
https://parameter1.freshdesk.com/a/tickets/490 https://www.pivotaltracker.com/story/show/176753327
=> Fix digital editions

tenants/multi/config/email-x.js, tenants/multi/templates/id-video-showcase.marko
https://www.pivotaltracker.com/n/projects/2467321 & https://parameter1.freshdesk.com/a/tickets/482
=> Setup new ID Video Showcase newsletter

packages/common/components/blocks/footer/index.marko, packages/common/components/blocks/footer/marko.json, tenants/multi/templates/cen-today.marko
=> Make please contact email & name configurable

tenants/multi/config/email-x.js, tenants/multi/config/gam.js, tenants/multi/templates/manufacturing-today-safety.marko
=> Add "Manufacturing Today - Safety" newsletter

tenants/multi/templates/manufacturing-today-safety.marko
=> Update text ad button link style

tenants/multi/config/email-x.js, tenants/multi/templates/design-development-today.marko, tenants/multi/templates/design-development-update.marko, tenants/multi/templates/design-development-weekly.marko
=> Update DDT newsletter headers & add a weekly newsletter

tenants/multi/templates/design-development-today.marko, tenants/multi/templates/design-development-update.marko, tenants/multi/templates/design-development-weekly.marko
=> convert header to display white background for ddt

tenants/multi/config/email-x.js, tenants/multi/templates/fm-weekly.marko
=> initial setup for fm weekly newsletter

packages/common/components/blocks/content/feed-full.marko, packages/common/components/blocks/content/grid.marko, packages/common/components/blocks/content/promotion-half.marko
Reverts parameter1/industrial-media-newsletters#67
=> Revert "Update image size calls"

packages/common/components/blocks/content/promotion-half.marko, packages/common/components/static-styles.marko
=> Update ad in mobile view

packages/common/components/blocks/content/promotion-half.marko, packages/common/components/static-styles.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/fm-weekly.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-insider.marko, tenants/multi/templates/manufacturing-today-safety.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko
=> Mobile view ad update

packages/common/components/blocks/content/promotion-half.marko, packages/common/components/static-styles.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/fm-weekly.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-insider.marko, tenants/multi/templates/manufacturing-today-safety.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko
Reverts parameter1/industrial-media-newsletters#70
=> Revert "Mobile view ad update"

packages/common/components/blocks/footer/index.marko, packages/common/components/blocks/footer/marko.json, tenants/multi/templates/cen-today.marko
=> Update advertise link CEN

tenants/multi/templates/industrial-technology-today.marko
=> Insert stealth link into Industrial Tech Today NL.

tenants/multi/templates/industrial-technology-today.marko
on Industrial Technology Today newsletter
=> Add teaser to bottom feed block

tenants/multi/templates/food-video-showcase.marko, tenants/multi/templates/id-video-showcase.marko, tenants/multi/templates/impo-video-showcase.marko, tenants/multi/templates/video-showcase.marko
=> Update all video showcase templates to show name on web-tab

tenants/multi/config/core.js, tenants/multi/config/email-x.js, tenants/multi/config/gam.js, tenants/multi/templates/today-medical-design-development.marko
=> Create Today in Medical Design & Development newsletter

tenants/multi/templates/today-medical-design-development.marko
=> Change footer information to use 'Lynch Media'

packages/common/components/blocks/content/featured-full.marko, packages/common/components/blocks/content/featured-half.marko, packages/common/components/blocks/content/feed-full.marko, packages/common/components/blocks/content/grid.marko, packages/common/components/blocks/content/promotion-half.marko, packages/common/package.json, packages/common/utils/watermark-display.js, tenants/multi/templates/digital-edition.marko, tenants/multi/templates/fm-product-showcase.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/fm-weekly.marko, tenants/multi/templates/id-digital-edition.marko, tenants/multi/templates/id-product-showcase.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-insider.marko, tenants/multi/templates/impo-mag-product-showcase.marko, tenants/multi/templates/manufacturing-product-showcase.marko, tenants/multi/templates/manufacturing-today-safety.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/mbt-product-showcase.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko, tenants/multi/templates/product-showcase.marko
Select template need to be adjusted/updated to utilize the shared components where possible, this will be done in a separate PR.
=> Playbutton overlay on Video Content items in newsletters.

tenants/multi/config/email-x.js, tenants/multi/config/gam.js, tenants/multi/templates/imts-weekly.marko
=> Create IMTS Weekly Newsletter

tenants/multi/config/email-x.js, tenants/multi/templates/design-development-weekly-comp.marko, tenants/multi/templates/manufacturing-weekly-comp.marko
=> Create DDT & Manufacturing Weekly Comp

packages/common/components/blocks/content/featured-half.marko, packages/common/components/blocks/content/feed-full.marko, packages/common/components/blocks/content/promotion-half.marko, tenants/multi/templates/digital-edition.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/fm-weekly.marko, tenants/multi/templates/id-digital-edition.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-insider.marko, tenants/multi/templates/imts-weekly.marko, tenants/multi/templates/manufacturing-today-safety.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/manufacturing-weekly-comp.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko
Currently it is quadrupling the image size on mobile
=> Change image options to w:330 

tenants/multi/config/email-x.js, tenants/multi/templates/mdd-video-showcase.marko
=> Mdd video showcase template

tenants/multi/config/email-x.js, tenants/multi/templates/id-ma-monthly.marko
=> Create ID - M&A Monthly newsletter

tenants/multi/templates/fm-weekly-tim-podcast.marko, tenants/multi/templates/ien-weekly-tim-podcast.marko
=> Remove ‘extra’ line/image breaks

tenants/multi/config/email-x.js
=> Add header ad slot to TIM Podcast newsletters

tenants/multi/config/email-x.js, tenants/multi/templates/manufacturing-security-breach.marko
=> Create Security Breach newsletter

packages/common/components/blocks/content/feed-full.marko, packages/common/components/blocks/content/promotion-half.marko, tenants/multi/templates/fm-today.marko, tenants/multi/templates/fm-weekly-tim-podcast.marko, tenants/multi/templates/fm-weekly.marko, tenants/multi/templates/id-ma-monthly.marko, tenants/multi/templates/id-today.marko, tenants/multi/templates/impo-insider.marko, tenants/multi/templates/imts-weekly.marko, tenants/multi/templates/manufacturing-security-breach.marko, tenants/multi/templates/manufacturing-today-safety.marko, tenants/multi/templates/manufacturing-today.marko, tenants/multi/templates/manufacturing-weekly-comp.marko, tenants/multi/templates/mbt-today.marko, tenants/multi/templates/newswire.marko
=> Adjust styling of text ad button

tenants/multi/config/email-x.js, tenants/multi/templates/ien-digi-key-integrator.marko
=> Create 'Digi-key' newsletter

tenants/multi/templates/ien-digi-key-integrator.marko
=> Replace digi-key header

.github/workflows/deploy-production.yml
Missed in: https://github.com/parameter1/industrial-media-newsletters/pull/147
=> Correct build and deploy tenant matrices

tenants/multi/config/email-x.js
=> Update email-x URIs

tenants/multi/templates/ien-today.marko
=> Remove non-functional duplicate block for Featured Video IEN Today
